name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Preprocess Markdown Files
        run: |
          mkdir -p build
          cp Lectures/*.md build/
          python preprocess.py build/
          
      - name: Render HTML from Preprocessed Files
        run: |
          cd build
          for file in *.md; do
            if [ -f "$file" ]; then
              quarto render "$file" --to html --output-dir ../Lectures
            fi
          done

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Lectures
          publish_branch: gh-pages
